/* global describe, it */
let chai = require('chai')
let expect = chai.expect
let { Graph } = require('..')

describe('Graph creation', () => {
  it('Graph created, nodes and edge added, node removed', () => {
    let gr = Graph.create()
    let n1 = gr.node('n1')
    let n2 = gr.node('n2')
    let e1 = gr.edge(n1, n2, 'e1')
    let e2 = gr.edge(n2, n1, 'e2')
    expect(n1.data).to.equal('n1')
    expect(n2.data).to.equal('n2')
    expect(e1.data).to.equal('e1')
    expect(gr.nodes.length).to.equal(2)
    expect(gr.nodes).to.include(n1)
    expect(gr.nodes).to.include(n2)
    expect(gr.edges.length).to.equal(2)
    expect(gr.edges).to.include(e1)
    expect(n1.edges).to.include(e1)
    expect(n2.edges).to.include(e1)
    n2.remove()
    expect(gr.nodes.length).to.equal(1)
    expect(gr.edges.length).to.equal(0)
    expect(n1.edges.length).to.equal(0)
    let n3 = gr.node('n3')
    let e3 = gr.edge(n1, n3, 'e3')
    expect(gr.nodes.length).to.equal(2)
    expect(gr.edges.length).to.equal(1)
    expect(n1.edges).to.include(e3)
    expect(n3.edges).to.include(e3)
    e3.remove()
    expect(gr.nodes.length).to.equal(2)
    expect(gr.edges.length).to.equal(0)
    expect(n1.edges.length).to.equal(0)
    expect(n3.edges.length).to.equal(0)
  })
})

describe('toJSON', () => {
  it('Graph to/from json', () => {
    let gr = Graph.create()
    let n1 = gr.node('n1')
    let n2 = gr.node('n2')
    let n3 = gr.node('n3')
    let e1 = gr.edge(n1, n2, 'e1')
    let e2 = gr.edge(n2, n3, 'e2')
    let grj = gr.toJSON()
    expect(grj.length).to.equal(gr.nodes.length + gr.edges.length)

    let gr2 = Graph.create(JSON.stringify(gr))
    expect(gr2.nodes.length).to.equal(gr.nodes.length)
    expect(gr2.edges.length).to.equal(gr.edges.length)
  })
})